# Generated by Django 5.2.4 on 2025-08-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_paymentmethod_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_dubbed',
            new_name='is_IMAX',
        ),
    ]
