# Generated by Django 5.2.4 on 2025-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_booking_payment_booking_status_alter_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
    ]
