# Generated by Django 5.2.4 on 2025-08-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_payment', to='movies.payment'),
        ),
    ]
