# Generated by Django 5.2.4 on 2025-08-10 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_booking_status_alter_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.booking'),
            preserve_default=False,
        ),
    ]
